import React from 'react';
import { modularToolComponents } from '../../tools';

// Dynamic lazy loaders for grouped category components
const lazyDev = (key: string) => React.lazy(() => import('./DevTools').then(m => ({ default: m.devToolsComponents[key] })));
const lazyDesign = (key: string) => React.lazy(() => import('./DesignTools').then(m => ({ default: m.designToolsComponents[key] })));
const lazyImage = (key: string) => React.lazy(() => import('./ImageTools').then(m => ({ default: m.imageToolsComponents[key] })));
const lazyText = (key: string) => React.lazy(() => import('./TextTools').then(m => ({ default: m.textToolsComponents[key] })));
const lazyPdf = (key: string) => React.lazy(() => import('./PdfTools').then(m => ({ default: m.pdfToolsComponents[key] })));
const lazyColor = (key: string) => React.lazy(() => import('./ColorTools').then(m => ({ default: m.colorToolsComponents[key] })));
const lazyConverter = (key: string) => React.lazy(() => import('./ConverterTools').then(m => ({ default: m.converterToolsComponents[key] })));
const lazyGenerator = (key: string) => React.lazy(() => import('./GeneratorTools').then(m => ({ default: m.generatorToolsComponents[key] })));
const lazySecurity = (key: string) => React.lazy(() => import('./SecurityTools').then(m => ({ default: m.securityToolsComponents[key] })));
const lazySeo = (key: string) => React.lazy(() => import('./SeoTools').then(m => ({ default: m.seoToolsComponents[key] })));
const lazyUtility = (key: string) => React.lazy(() => import('./UtilityTools').then(m => ({ default: m.utilityToolsComponents[key] })));

// Dynamic lazy loaders for newly batched tools / collections
const lazyNewDev = (exportName: string) => React.lazy(() => import('./NewDevTools').then(m => ({ default: m[exportName] })));
const lazyNewDev30 = (exportName: string) => React.lazy(() => import('./NewDevTools30').then(m => ({ default: m[exportName] })));
const lazyAdvanced = (exportName: string) => React.lazy(() => import('./AdvancedToolsCollection').then(m => ({ default: m[exportName] })));
const lazyNewToolsBatch = (exportName: string) => React.lazy(() => import('./NewToolsBatch').then(m => ({ default: m[exportName] })));

// Core heavy components
const LazyVideoStudio = React.lazy(() => import('./VideoStudio').then(m => ({ default: m.VideoStudio })));
const LazyQualityEnhancer = React.lazy(() => import('./QualityEnhancer').then(m => ({ default: m.QualityEnhancer })));

export const allToolComponents: Record<string, React.ComponentType<any>> = {
  // Category standard tools
  'uuid-gen': lazyDev('uuid-gen'),
  'base64-codec': lazyDev('base64-codec'),
  'url-codec': lazyDev('url-codec'),
  'json-validator': lazyDev('json-validator'),
  'regex-tester': lazyDev('regex-tester'),
  'html-entities': lazyDev('html-entities'),
  'jwt-decoder': lazyDev('jwt-decoder'),
  'key-detector': lazyDev('key-detector'),
  'html-beautifier': lazyDev('html-beautifier'),

  // Design tools category
  'box-shadow-gen': lazyDesign('box-shadow-gen'),
  'border-radius-gen': lazyDesign('border-radius-gen'),
  'glassmorphism-gen': lazyDesign('glassmorphism-gen'),
  'neumorphism-gen': lazyDesign('neumorphism-gen'),
  'button-gen': lazyDesign('button-gen'),
  'svg-blob-gen': lazyDesign('svg-blob-gen'),
  'canvas-scratch': lazyDesign('canvas-scratch'),
  'css-gradient-gen': lazyDesign('css-gradient-gen'),
  'shadow-generator': lazyDesign('box-shadow-gen'),
  'border-radius': lazyDesign('border-radius-gen'),
  'gradient-generator': lazyDesign('css-gradient-gen'),
  'cubic-bezier': lazyDesign('glassmorphism-gen'),
  'aspect-ratio': lazyDesign('glassmorphism-gen'),

  // Image tools category
  'image-editor': lazyImage('image-editor'),
  'img-compressor': lazyImage('img-compressor'),
  'img-resizer': lazyImage('img-resizer'),
  'img-converter': lazyImage('img-converter'),
  'favicon-gen': lazyImage('favicon-gen'),
  'image-filter': lazyImage('image-filter'),
  'crop-tool': lazyImage('crop-tool'),
  'image-compressor': lazyImage('img-compressor'),
  'image-resizer': lazyImage('img-resizer'),
  'image-converter': lazyImage('img-converter'),
  'image-filters': lazyImage('image-filter'),
  'image-cropper': lazyImage('crop-tool'),
  'exif-reader': lazyImage('image-editor'),
  'color-picker': lazyImage('image-editor'),
  'image-splitter': lazyImage('image-editor'),
  'qr-scanner': lazyImage('image-editor'),

  // Text tools category
  'word-counter': lazyText('word-counter'),
  'case-converter': lazyText('case-converter'),
  'lorem-gen': lazyText('lorem-gen'),
  'text-compare': lazyText('text-compare'),
  'find-replace': lazyText('find-replace'),
  'markdown-preview': lazyText('markdown-preview'),
  'rot13-reverser': lazyText('rot13-reverser'),
  'lorem-ipsum': lazyText('lorem-gen'),
  'text-diff': lazyText('text-compare'),
  'string-escaper': lazyText('case-converter'),
  'text-analyzer-basic': lazyText('word-counter'),
  'slug-generator': lazyText('case-converter'),
  'obfuscator': lazyText('rot13-reverser'),

  // Pdf tools category
  'text-to-pdf': lazyPdf('text-to-pdf'),
  'img-to-pdf': lazyPdf('img-to-pdf'),
  'img-to-pdf-basic': lazyPdf('img-to-pdf'),
  'pdf-viewer': lazyPdf('text-to-pdf'),
  'pdf-merger': lazyPdf('text-to-pdf'),
  'pdf-splitter': lazyPdf('text-to-pdf'),
  'pdf-to-img': lazyPdf('text-to-pdf'),
  'pdf-encrypt': lazyPdf('text-to-pdf'),
  'pdf-decrypt': lazyPdf('text-to-pdf'),
  'pdf-compress-basic': lazyPdf('text-to-pdf'),
  'pdf-metadata': lazyPdf('text-to-pdf'),

  // Color tools category
  'color-palette': lazyColor('color-palette'),
  'contrast-checker': lazyColor('contrast-checker'),
  'color-blender': lazyColor('color-blender'),
  'color-picker-tool': lazyColor('color-picker-tool'),
  'color-shades': lazyColor('color-shades'),
  'color-converter': lazyColor('color-palette'),
  'color-contrast': lazyColor('contrast-checker'),
  'color-mixer-basic': lazyColor('color-blender'),
  'color-blindness': lazyColor('color-palette'),
  'color-extractor': lazyColor('color-palette'),
  'color-palette-gen': lazyColor('color-palette'),
  'color-wheel': lazyColor('color-palette'),
  'color-names': lazyColor('color-palette'),

  // Converter tools category
  'unit-converter': lazyConverter('unit-converter'),
  'timestamp-conv': lazyConverter('timestamp-conv'),
  'json-csv-conv': lazyConverter('json-csv-conv'),
  'md-html-conv': lazyConverter('md-html-conv'),
  'epoch-converter-basic': lazyConverter('timestamp-conv'),
  'csv-to-json': lazyConverter('json-csv-conv'),
  'json-to-csv-basic': lazyConverter('json-csv-conv'),
  'xml-to-json-basic': lazyConverter('json-csv-conv'),
  'json-to-xml-basic': lazyConverter('json-csv-conv'),
  'base64-to-file': lazyConverter('json-csv-conv'),
  'file-to-base64': lazyConverter('json-csv-conv'),
  'hex-to-rgb': lazyConverter('json-csv-conv'),

  // Generator tools category
  'password-gen': lazyGenerator('password-gen'),
  'qr-gen': lazyGenerator('qr-gen'),
  'barcode-gen': lazyGenerator('barcode-gen'),
  'num-gen': lazyGenerator('num-gen'),
  'random-picker': lazyGenerator('random-picker'),
  'qr-generator': lazyGenerator('qr-gen'),
  'barcode-generator': lazyGenerator('barcode-gen'),
  'uuid-v4': lazyGenerator('password-gen'),
  'placeholder-img': lazyGenerator('qr-gen'),
  'user-signature': lazyGenerator('random-picker'),
  'hash-generator': lazyGenerator('qr-gen'),
  'random-number': lazyGenerator('num-gen'),
  'fake-data': lazyGenerator('random-picker'),

  // Security tools category
  'hash-gen': lazySecurity('hash-gen'),
  'password-strength': lazySecurity('password-strength'),
  'key-gen': lazySecurity('key-gen'),
  'htpasswd-gen': lazySecurity('htpasswd-gen'),
  'hash-verifier': lazySecurity('hash-gen'),
  'symmetric-encryption': lazySecurity('hash-gen'),
  'asymmetric-keys': lazySecurity('key-gen'),
  'jwt-encoder-basic': lazySecurity('password-strength'),
  'url-sandbox': lazySecurity('password-strength'),
  'xss-filter': lazySecurity('password-strength'),
  'passphrase-generator': lazySecurity('password-strength'),
  'file-checksum': lazySecurity('hash-gen'),

  // Seo tools category
  'slug-gen': lazySeo('slug-gen'),
  'meta-tags': lazySeo('meta-tags'),
  'robots-gen': lazySeo('robots-gen'),
  'sitemap-gen': lazySeo('sitemap-gen'),
  'sitemap-generator': lazySeo('sitemap-gen'),
  'robots-txt': lazySeo('robots-gen'),
  'redirect-checker': lazySeo('slug-gen'),
  'broken-links': lazySeo('slug-gen'),
  'seo-slug': lazySeo('slug-gen'),
  'keyword-density': lazySeo('slug-gen'),
  'mobile-friendly': lazySeo('slug-gen'),
  'schema-markup': lazySeo('slug-gen'),

  // Utility tools category
  'percent-calc': lazyUtility('percent-calc'),
  'age-calc': lazyUtility('age-calc'),
  'bmi-calc': lazyUtility('bmi-calc'),
  'date-diff': lazyUtility('date-diff'),
  'stopwatch': lazyUtility('stopwatch'),
  'calculator': lazyUtility('percent-calc'),
  'timezone-converter': lazyUtility('stopwatch'),
  'percentage-calculator': lazyUtility('percent-calc'),
  'markdown-editor': lazyUtility('stopwatch'),
  'regex-cheat': lazyUtility('stopwatch'),
  'json-compare': lazyUtility('stopwatch'),
  'string-utilities': lazyUtility('stopwatch'),
  'ascii-table': lazyUtility('stopwatch'),

  // Media
  'video-studio': LazyVideoStudio,
  'media-quality-enhancer': LazyQualityEnhancer,

  // NewDevTools
  'json-formatter': lazyNewDev('JsonFormatter'),
  'json-minifier': lazyNewDev('JsonMinifier'),
  'css-formatter': lazyNewDev('CssFormatter'),
  'javascript-formatter': lazyNewDev('JavaScriptFormatter'),
  'sql-formatter': lazyNewDev('SqlFormatter'),
  'random-string-gen': lazyNewDev('RandomStringGen'),
  'svg-optimizer': lazyNewDev('SvgOptimizer'),
  'binary-converter': lazyNewDev('BinaryConverter'),

  // NewDevTools30
  'html-minifier': lazyNewDev30('HtmlMinifier'),
  'yaml-to-json': lazyNewDev30('YamlToJson'),
  'json-to-yaml': lazyNewDev30('JsonToYaml'),
  'toml-to-json': lazyNewDev30('TomlToJson'),
  'toml-generator': lazyNewDev30('TomlGenerator'),
  'base32-codec': lazyNewDev30('Base32Codec'),
  'rot13-codec': lazyNewDev30('Rot13Codec'),
  'hex-codec': lazyNewDev30('HexCodec'),
  'unicode-inspector': lazyNewDev30('UnicodeInspector'),
  'user-agent-parser': lazyNewDev30('UserAgentParser'),
  'url-parser': lazyNewDev30('UrlParser'),
  'html-xss-sanitizer': lazyNewDev30('HtmlXssSanitizer'),
  'device-info': lazyNewDev30('DeviceInfo'),
  'html-to-markdown': lazyNewDev30('HtmlToMarkdown'),
  'morse-converter': lazyNewDev30('MorseConverter'),
  'css-clip-path': lazyNewDev30('CssClipPath'),
  'cron-generator': lazyNewDev30('CronGenerator'),
  'color-palette-extractor': lazyNewDev30('ColorPaletteExtractor'),
  'port-scanner-simulator': lazyNewDev30('PortScannerSimulator'),
  'text-shuffler': lazyNewDev30('TextShuffler'),
  'decimal-binary': lazyNewDev30('DecimalBinary'),
  'regex-cheatsheet': lazyNewDev30('RegexCheatsheet'),
  'css-transform': lazyNewDev30('CssTransform'),
  'svg-to-jsx': lazyNewDev30('SvgToJsx'),
  'json-schema-gen': lazyNewDev30('JsonSchemaGen'),
  'js-obfuscator': lazyNewDev30('JsObfuscator'),
  'sql-minify': lazyNewDev30('SqlMinify'),
  'git-commands': lazyNewDev30('GitCommands'),
  'css-flexbox': lazyNewDev30('CssFlexbox'),
  'text-sorter': lazyNewDev30('TextSorter'),
  'curl-to-fetch': lazyNewDev30('CurlToFetch'),

  // AdvancedToolsCollection
  'jwt-debugger': lazyAdvanced('JwtDebugger'),
  'cron-parser': lazyAdvanced('CronParser'),
  'markdown-table-generator': lazyAdvanced('MarkdownTableGenerator'),
  'json-to-ts': lazyAdvanced('JsonToTs'),
  'json-to-csv': lazyAdvanced('JsonToCsv'),
  'seo-slug-extractor': lazyAdvanced('SeoSlugExtractor'),
  'aspect-ratio-calc': lazyAdvanced('AspectRatioCalc'),
  'password-entropy': lazyAdvanced('PasswordEntropy'),
  'color-contrast-checker': lazyAdvanced('ColorContrastChecker'),
  'cidr-calc': lazyAdvanced('CidrCalc'),
  'docker-compose': lazyAdvanced('DockerCompose'),
  'sql-mock-gen': lazyAdvanced('SqlMockGen'),

  // NewToolsBatch
  'xml-formatter': lazyNewToolsBatch('XmlFormatter'),
  'xml-validator': lazyNewToolsBatch('XmlValidator'),
  'xml-to-json': lazyNewToolsBatch('XmlToJson'),
  'json-to-xml': lazyNewToolsBatch('JsonToXml'),
  'yaml-formatter': lazyNewToolsBatch('YamlFormatter'),
  'yaml-validator': lazyNewToolsBatch('YamlValidator'),
  'csv-to-json-batch': lazyNewToolsBatch('CsvToJsonBatch'),
  'sql-formatter-advanced': lazyNewToolsBatch('SqlFormatterAdvanced'),
  'regex-builder': lazyNewToolsBatch('RegexBuilder'),
  'url-parser-advanced': lazyNewToolsBatch('UrlParserAdvanced'),
  'base64-image': lazyNewToolsBatch('Base64Image'),
  'binary-to-text': lazyNewToolsBatch('BinaryToText'),
  'git-ignore-gen': lazyNewToolsBatch('GitIgnoreGen'),
  'readme-generator': lazyNewToolsBatch('ReadmeGenerator'),
  'license-generator': lazyNewToolsBatch('LicenseGenerator'),
  'json-minify-advanced': lazyNewToolsBatch('JsonMinifyAdvanced'),
  'html-formatter-beautifier': lazyNewToolsBatch('HtmlFormatterBeautifier'),
  'text-analyzer': lazyNewToolsBatch('TextAnalyzer'),
  'text-cleaner': lazyNewToolsBatch('TextCleaner'),
  'text-case-invert': lazyNewToolsBatch('TextCaseInvert'),
  'text-slugify': lazyNewToolsBatch('TextSlugify'),
  'line-sorter': lazyNewToolsBatch('LineSorter'),
  'text-duplicate-remover': lazyNewToolsBatch('TextDuplicateRemover'),
  'binary-text-converter': lazyNewToolsBatch('BinaryTextConverter'),
  'morse-code': lazyNewToolsBatch('MorseCode'),
  'anagram-solver': lazyNewToolsBatch('AnagramSolver'),
  'word-scrambler': lazyNewToolsBatch('WordScrambler'),
  'leet-speak': lazyNewToolsBatch('LeetSpeak'),
  'text-reverser': lazyNewToolsBatch('TextReverser'),
  'markdown-to-html': lazyNewToolsBatch('MarkdownToHtml'),
  'html-to-text': lazyNewToolsBatch('HtmlToText'),
  'img-color-picker': lazyNewToolsBatch('ImgColorPicker'),
  'img-meta-reader': lazyNewToolsBatch('ImgMetaReader'),
  'img-contrast-adjust': lazyNewToolsBatch('ImgContrastAdjust'),
  'img-grayscale': lazyNewToolsBatch('ImgGrayscale'),
  'img-blur-filter': lazyNewToolsBatch('ImgBlurFilter'),
  'img-watermarker': lazyNewToolsBatch('ImgWatermarker'),
  'img-base64-encode': lazyNewToolsBatch('ImgBase64Encode'),
  'img-placeholder-gen': lazyNewToolsBatch('ImgPlaceholderGen'),
  'svg-pattern-gen': lazyNewToolsBatch('SvgPatternGen'),
  'favicon-converter': lazyNewToolsBatch('FaviconConverter'),
  'pdf-text-extract': lazyNewToolsBatch('PdfTextExtract'),
  'pdf-image-extract': lazyNewToolsBatch('PdfImageExtract'),
  'pdf-merge': lazyNewToolsBatch('PdfMerge'),
  'pdf-split': lazyNewToolsBatch('PdfSplit'),
  'pdf-compress': lazyNewToolsBatch('PdfCompress'),
  'pdf-metadata-viewer': lazyNewToolsBatch('PdfMetadataViewer'),
  'image-to-pdf': lazyNewToolsBatch('ImageToPdf'),
  'pdf-page-numberer': lazyNewToolsBatch('PdfPageNumberer'),
  'sha256-hasher': lazyNewToolsBatch('Sha256Hasher'),
  'sha512-hasher': lazyNewToolsBatch('Sha512Hasher'),
  'md5-hasher': lazyNewToolsBatch('Md5Hasher'),
  'sha1-hasher': lazyNewToolsBatch('Sha1Hasher'),
  'aes-encryption': lazyNewToolsBatch('AesEncryption'),
  'bcrypt-generator': lazyNewToolsBatch('BcryptGenerator'),
  'password-generator-pro': lazyNewToolsBatch('PasswordGeneratorPro'),
  'uuid-v4-gen': lazyNewToolsBatch('UuidV4Gen'),
  'jwt-generator-tool': lazyNewToolsBatch('JwtGeneratorTool'),
  'secure-key-gen': lazyNewToolsBatch('SecureKeyGen'),
  'unit-converter-pro': lazyNewToolsBatch('UnitConverterPro'),
  'epoch-converter': lazyNewToolsBatch('EpochConverter'),
  'cidr-calculator-pro': lazyNewToolsBatch('CidrCalculatorPro'),
  'cron-editor': lazyNewToolsBatch('CronEditor'),
  'color-mixer': lazyNewToolsBatch('ColorMixer'),
  'lorem-ipsum-pro': lazyNewToolsBatch('LoremIpsumPro'),
  'diff-checker-pro': lazyNewToolsBatch('DiffCheckerPro'),
  'dns-lookup-simulator': lazyNewToolsBatch('DnsLookupSimulator'),

  // 33 Media Production Tools (routed directly to VideoStudio with props)
  'video-cutter': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'cutter' }),
  'video-trimmer': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'trimmer' }),
  'video-splitter': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'splitter' }),
  'video-merger': () => React.createElement(LazyVideoStudio, { initialTab: 'timeline', initialQuickTool: 'merger' }),
  'video-compressor': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'compressor' }),
  'video-converter': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'converter' }),
  'video-cropper': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'cropper' }),
  'video-resizer': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'resizer' }),
  'video-rotator': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'rotator' }),
  'video-speed-controller': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'speed' }),
  'frame-extractor': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'frame-extract' }),
  'thumbnail-generator': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'thumbnail' }),
  'gif-creator': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'gif' }),
  'video-metadata-viewer': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'metadata' }),
  'video-metadata-remover': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'metadata-remove' }),
  'aspect-ratio-converter': () => React.createElement(LazyVideoStudio, { initialTab: 'timeline', initialQuickTool: 'aspect-ratio' }),
  'subtitle-editor': () => React.createElement(LazyVideoStudio, { initialTab: 'audio-subs', initialQuickTool: 'subtitles' }),
  'srt-vtt-converter': () => React.createElement(LazyVideoStudio, { initialTab: 'audio-subs', initialQuickTool: 'subtitle-format' }),
  'audio-cutter': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'audio-cut' }),
  'audio-merger': () => React.createElement(LazyVideoStudio, { initialTab: 'timeline', initialQuickTool: 'audio-merge' }),
  'audio-converter': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'audio-convert' }),
  'audio-compressor': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'audio-compress' }),
  'audio-extractor': () => React.createElement(LazyVideoStudio, { initialTab: 'audio-subs', initialQuickTool: 'audio-extract' }),
  'volume-normalizer': () => React.createElement(LazyVideoStudio, { initialTab: 'audio-subs', initialQuickTool: 'volume' }),
  'audio-waveform-viewer': () => React.createElement(LazyVideoStudio, { initialTab: 'audio-subs', initialQuickTool: 'waveform' }),
  'audio-metadata-tools': () => React.createElement(LazyVideoStudio, { initialTab: 'audio-subs', initialQuickTool: 'audio-meta' }),
  'video-format-presets': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'presets' }),
  'social-media-video-resize': () => React.createElement(LazyVideoStudio, { initialTab: 'quick-tools', initialQuickTool: 'social' }),
  'caption-tools': () => React.createElement(LazyVideoStudio, { initialTab: 'audio-subs', initialQuickTool: 'captioning' }),
  'text-overlay-tools': () => React.createElement(LazyVideoStudio, { initialTab: 'overlays', initialQuickTool: 'text' }),
  'watermark-tools': () => React.createElement(LazyVideoStudio, { initialTab: 'overlays', initialQuickTool: 'watermark' }),
  'basic-video-effects': () => React.createElement(LazyVideoStudio, { initialTab: 'timeline', initialQuickTool: 'effects' }),
  'timeline-utilities': () => React.createElement(LazyVideoStudio, { initialTab: 'timeline', initialQuickTool: 'utils' }),

  // Load new modular tools from their registry
  ...modularToolComponents
};
